"""Email alerting system for critical threats."""

import smtplib
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List
from pathlib import Path
from . import database

# Load email config from file or use defaults
CONFIG_FILE = Path(__file__).parent.parent / "email_config.json"

DEFAULT_CONFIG = {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "sender_email": "your-email@gmail.com",
    "sender_password": "your-app-password",
    "enabled": False
}


def load_config() -> dict:
    """Load email configuration from file."""
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, "r") as f:
                return json.load(f)
        except Exception:
            return DEFAULT_CONFIG
    return DEFAULT_CONFIG


def save_config(config: dict) -> bool:
    """Save email configuration to file."""
    try:
        with open(CONFIG_FILE, "w") as f:
            json.dump(config, f, indent=2)
        return True
    except Exception:
        return False


def send_critical_threat_alert(recipient_email: str, ip_address: str, threat_data: dict) -> bool:
    """Send an email alert for a critical threat."""
    config = load_config()

    if not config.get("enabled", False):
        return False

    try:
        # Create email message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"🚨 CRITICAL THREAT ALERT: {ip_address}"
        msg["From"] = config["sender_email"]
        msg["To"] = recipient_email

        # Plain text version
        text = f"""
AMADIOHA THREAT ALERT
====================

CRITICAL THREAT DETECTED

IP Address: {ip_address}
Threat Type: {threat_data.get('threat_type', 'Unknown')}
Reputation Score: {threat_data.get('reputation_score', 0)}/100
Abuse Reports: {threat_data.get('abuse_reports', 0)}

Action Required:
- Review firewall logs
- Consider blocking this IP
- Investigate any suspicious activity

Generated by: Amadioha Cyber Defense v0.2.0
        """

        # HTML version
        html = f"""
        <html>
          <body style="font-family: Arial, sans-serif;">
            <div style="background: #f5f5f5; padding: 20px; border-radius: 8px;">
              <h1 style="color: #dc3545;">🚨 CRITICAL THREAT ALERT</h1>
              <div style="background: white; padding: 20px; border-radius: 8px;">
                <p><strong>IP Address:</strong> <code>{ip_address}</code></p>
                <p><strong>Threat Type:</strong> {threat_data.get('threat_type', 'Unknown')}</p>
                <p><strong>Reputation Score:</strong> {threat_data.get('reputation_score', 0)}/100</p>
                <p><strong>Abuse Reports:</strong> {threat_data.get('abuse_reports', 0)}</p>
                <p><strong>Known for Attacks:</strong> {'Yes' if threat_data.get('known_for_attacks') else 'No'}</p>
              </div>
              <div style="margin-top: 20px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666;">
                <p>Generated by Amadioha Cyber Defense v0.2.0</p>
              </div>
            </div>
          </body>
        </html>
        """

        # Attach both plain text and HTML
        msg.attach(MIMEText(text, "plain"))
        msg.attach(MIMEText(html, "html"))

        # Send email
        with smtplib.SMTP(config["smtp_server"], config["smtp_port"]) as server:
            server.starttls()
            server.login(config["sender_email"], config["sender_password"])
            server.send_message(msg)

        # Log alert in database
        database.save_email_alert(
            recipient_email,
            ip_address,
            threat_data.get("threat_type"),
            "CRITICAL")

        return True

    except Exception as e:
        print(f"Failed to send email alert: {e}")
        return False


def send_brute_force_summary(recipient_email: str, threats: List[dict], log_file: str) -> bool:
    """Send a summary email of brute force attempts."""
    config = load_config()

    if not config.get("enabled", False):
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = "🔐 Brute Force Summary Report"
        msg["From"] = config["sender_email"]
        msg["To"] = recipient_email

        # Plain text version
        threat_list = "\n".join([
            f"  - {t['ip']}: {t['attempts']} attempts ({t['threat_type']})"
            for t in sorted(threats, key=lambda x: x['attempts'], reverse=True)[:10]
        ])

        text = f"""
BRUTE FORCE SUMMARY REPORT
===========================

Log File: {log_file}
Total Attacking IPs: {len(threats)}

Top Attackers:
{threat_list}

Please review these IPs and consider adding them to your firewall blocklist.

Generated by: Amadioha Cyber Defense v0.2.0
        """

        # HTML version
        rows = "\n".join([
            f"<tr><td>{t['ip']}</td><td>{t['attempts']}</td><td>{t['threat_type']}</td><td>{t['reputation_score']}</td></tr>"
            for t in sorted(threats, key=lambda x: x['attempts'], reverse=True)[:10]
        ])

        html = f"""
        <html>
          <body style="font-family: Arial, sans-serif;">
            <div style="background: #f5f5f5; padding: 20px; border-radius: 8px;">
              <h1 style="color: #0d6efd;">🔐 Brute Force Summary Report</h1>
              <p>Log File: <code>{log_file}</code></p>
              <p><strong>Total Attacking IPs:</strong> {len(threats)}</p>
              <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                <thead style="background: #0d6efd; color: white;">
                  <tr>
                    <th style="padding: 10px; border: 1px solid #ddd;">IP Address</th>
                    <th style="padding: 10px; border: 1px solid #ddd;">Attempts</th>
                    <th style="padding: 10px; border: 1px solid #ddd;">Threat Type</th>
                    <th style="padding: 10px; border: 1px solid #ddd;">Score</th>
                  </tr>
                </thead>
                <tbody>
                  {rows}
                </tbody>
              </table>
              <div style="margin-top: 20px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666;">
                <p>Generated by Amadioha Cyber Defense v0.2.0</p>
              </div>
            </div>
          </body>
        </html>
        """

        msg.attach(MIMEText(text, "plain"))
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(config["smtp_server"], config["smtp_port"]) as server:
            server.starttls()
            server.login(config["sender_email"], config["sender_password"])
            server.send_message(msg)

        database.save_email_alert(recipient_email, "multiple", "brute_force_summary", "HIGH")

        return True

    except Exception as e:
        print(f"Failed to send summary email: {e}")
        return False


def configure_email(smtp_server: str, smtp_port: int, sender_email: str,
                    sender_password: str, enabled: bool = True) -> bool:
    """Configure email settings."""
    config = {
        "smtp_server": smtp_server,
        "smtp_port": smtp_port,
        "sender_email": sender_email,
        "sender_password": sender_password,
        "enabled": enabled
    }
    return save_config(config)


if __name__ == "__main__":
    print("Email Alert System")
    print("Config file:", CONFIG_FILE)
    config = load_config()
    print("Current config:", config)
